### ISSUE TITLE
某些重要的网站被屏蔽了

### ISSUE THREAD

**Issue by ikkyusan123** [ligyxy/Blocklist#1]
发现tieba.baidu.com、www.kafan.cn、bbs.kafan.cn这些重要的网站都被屏蔽了，望改进。

**Comment by gyli** [comment]
感谢反馈。

屏蔽这些网站是有意为之。在这个帖子中你可以看到建立这份列表的初衷 https://www.v2ex.com/t/286059

简单地说，我从百度知道，kfan这些网站几乎不能获取到有用的信息。但我也提到，这样的列表应该是很私人化的文件。如果不巧你和我的信息过滤强度不同，建议你 Fork 本列表，再从中删减。这份列表并没有很多二级或三级域名，应该不难处理。
