### ISSUE TITLE
订阅网址无效

### ISSUE THREAD

**Issue by jiahe224** [ligyxy/Blocklist#10]
ublacklist为最新版本，添加订阅时网址无效，换了一个 .txt 结尾的地址后可添加，可添加网址为 https://raw.githubusercontent.com/cobaltdisco/Google-Chinese-Results-Blocklist/master/uBlacklist_subscription.txt

**Comment by gyli** [comment]
抱歉我没有明白你提的问题。你指的是该项目首页中提到的列表链接无效吗？即 https://raw.githubusercontent.com/ligyxy/Blocklist/master/BLOCKLIST_uBlacklist
我已检查过，这个链接是工作正常的。

你附上的链接是另一个项目的列表，与本项目无关。

**Comment by jiahe224** [comment]
> 抱歉我没有明白你提的问题。你指的是该项目首页中提到的列表链接无效吗？即 https://raw.githubusercontent.com/ligyxy/Blocklist/master/BLOCKLIST_uBlacklist 我已检查过，这个链接是工作正常的。
> 
> 你附上的链接是另一个项目的列表，与本项目无关。

网址是正常的，可打开，但用在订阅上时无效，貌似得带扩展名才行

**Comment by gyli** [comment]
感谢说明！但是我多次测试无法复现这个问题，怀疑列表较长，恐怕内存不够导致的迟缓。
但我也上传了一份带后缀的文件，也不妨试试 https://raw.githubusercontent.com/ligyxy/Blocklist/with-extension/BLOCKLIST_uBlacklist.txt

**Comment by jiahe224** [comment]
> 感谢说明！但是我多次测试无法复现这个问题，怀疑列表较长，恐怕内存不够导致的迟缓。 但我也上传了一份带后缀的文件，也不妨试试 https://raw.githubusercontent.com/ligyxy/Blocklist/with-extension/BLOCKLIST_uBlacklist.txt

刚又试了原链接可以添加，可能是由于第一次安装后没重启的原因
