### ISSUE TITLE
I maybe using your list.

### ISSUE THREAD

**Issue by smokingwheels** [ligyxy/Blocklist#2]
I followed the advise of W3K it makes it easer to download for the Pi-Hole.

W3K said.
We’d suggest checking out GH pages. It’s free and PH won’t redownload the blocklist if there’s no new changes  - W3K
[https://twitter.com/The_Pi_Hole/status/920758922121641984](https://twitter.com/The_Pi_Hole/status/920758922121641984)

If you would like to have a special note could you create an issue, I have also done work on you list to make it more acceptable for the Pi-hole.
[https://github.com/smokingwheels/smokingwheels.github.io](https://github.com/smokingwheels/smokingwheels.github.io)
At the moment I need a bit of time to relax and have a rest.

**Comment by gyli** [comment]
I am glad that you are using this block list and feel free to fork or copy it.

**Comment by smokingwheels** [comment]
Thank you.
Have you heard of a Pi-Hole?
[https://pi-hole.net/](https://pi-hole.net/)
