### ISSUE TITLE
Google Personal Blocklist 失效了吧？

### ISSUE THREAD

**Issue by Shuumatsu** [ligyxy/Blocklist#5]

**Comment by Caldis** [comment]
https://chrome.google.com/webstore/detail/search-blocklist/lmmlebipfkjpbddppdkobgfonflpifkk
这个可以替代

**Comment by jostyee** [comment]
推荐 https://github.com/iorate/uBlacklist

**Comment by gyli** [comment]
@jostyee 就我个人的体验来说，uBlacklist只能接受正则表达式条目，条目超过上万条后就很难加载和运行了。上面的Search Blocklist是目前看来最接近Google Personal Blocklist的替代品。

**Comment by jostyee** [comment]
@ligyxy 因为我用Firefox，ublacklist有addon。。

**Comment by Shuumatsu** [comment]
现在这些替代品好像也只是在前端隐藏了搜索结果吧？可能会导致第一页搜索结果只有一两条

**Comment by gyli** [comment]
@Shuumatsu 囿于拓展的实现方式，Google自家的Personal Blocklist也只是屏蔽结果，也会有只有一两条结果的可能。这可能不是拓展能解决的问题。

**Comment by Shuumatsu** [comment]
> @Shuumatsu 囿于拓展的实现方式，Google 自家的 Personal Blocklist 也只是屏蔽结果，也会有只有一两条结果的可能。这可能不是拓展能解决的问题。

因为我是使用了这些替代品之后才感觉到第一页内容明显变少了而且 Personal Blocklist 是 Google 自家的 所以我怀疑以前 Google 会为当前账户在服务端记录扩展上设置的规则或者篡改了发送的请求之类的 
（当然也可能因为 Personal Blocklist 失效挺久了我记错了

**Comment by Caldis** [comment]
@Shuumatsu 以前的也是简单的在结果页面跑一下 filter...

**Comment by danny0838** [comment]
可以參考看看[終結內容農場](https://github.com/danny0838/content-farm-terminator)，設計上就是專門對付垃圾網站的，除了在搜尋結果標示垃圾網站，也有防止進入的功能。

**Comment by gyli** [comment]
@danny0838 你的过滤列表有做垃圾分类，看起来很棒。不过似乎维护成本也就高很多。

**Comment by danny0838** [comment]
@gyli 垃圾分類真是微妙的說法兒XD

其實有時正好相反，適當分類才方便管理。如果不分類，有些網站後來就容易搞不清楚當初為何封鎖。

你的名單大概有一半的網址失效，還有很多不知為何封鎖的（像 blogspot.com…很多大牛都用這個啊…），可能還要檢查很久才能拿來用XDD

**Comment by gyli** [comment]
@danny0838 blogspot.com 这样的情况是误杀，已经更正。但我使用的是搜索特点关键词加一点人工检查的办法来寻找垃圾站，总是有一些误杀的情况，恐怕我需要在目前的工序中再补充一个白名单检查的过程。

网址失效目前还不是太大问题。有些垃圾站的存在时间不长，尤其是用作 SEO 目的的垃圾站。导致这样的列表时效性很强。不过这些失效域名并不会有多少误杀的情况，目前的插件也有能力处理这样长度的列表，因此我不认为是太大问题。未来可以通过批量 WHOIS 查询的办法把过期域名排除。

由于我想要做的是一份足够自动化的脚本来增补这份列表，恐怕没有足够的时间和人力花在分类与人工检查上，除非分类的部分也能够有某种自动识别的方法。

**Comment by danny0838** [comment]
@gyli 原來如此。但我還是看不太懂這名單的篩選原則。就以 7b3cd7bd9033e515d72c0fc15f91bf9234cd9687 新增的網域為例，5566vx.com 是因為交易微信號違法？h5v7x.biz 連不上，不知為何加黑？z29d.com 是因為沒有備案號？

**Comment by gyli** [comment]
@danny0838 这份列表是针对在 Google 搜索结果里出现的无关或仿冒的网站。因此我并不在乎网站内容是否违法，也不太在乎其首页内容。

因为无法追回当时添加的原因，我没法还原这些域名是因为什么关键词而上榜。但添加条目有几个主要原因：
网站是 SEO 站群的一部分，内容是抓取的其他网站正常内容；
直接抓取或者机器翻译其他网站的内容农场；
网站被黑，被添加了无关的文本、链接、转跳等，这些内容又被 Google 爬取。

另外要注意，这份列表基本只列出主域名，但出问题的页面可能存在于次级域名或者次级目录，因此不能以首页内容为准。在你给的几个域名中，www3.z29d.com 即是一个二级域名的例子，它和其主域名实际也是 SEO 站群一部分。

**Comment by danny0838** [comment]
@gyli 原來如此。你提到列表是自動化生成，但 Google 搜尋是有防機器人機制的，不曉得你是怎麼自動化取得 Google 搜尋結果的？有現成的 API 可以使用嗎？

**Comment by gyli** [comment]
@danny0838 我并没有可用的 API。抱歉我也不能透露方法和代码。使用脚本抓取搜索结果从 Google 的角度看是滥用。 但是应该说我目前也没能多么自动地搜索新的域名，还是需要很多手动的部分。
