### ISSUE TITLE
pinterest.com False Positive

### ISSUE THREAD

**Issue by p1r473** [ligyxy/Blocklist#8]
Hi, this blocks social media site Pinterest.

**Comment by danny0838** [comment]
I cannot reproduce the issue. Can you provide a URL of Pininterest page that is blocked?

**Comment by p1r473** [comment]
You are blocking pinterest.com
https://github.com/gyli/Blocklist/blob/master/BLOCKLIST#L46468
This is a popular social media.

**Comment by gyli** [comment]
@p1r473 Interesting, it comes back again! It's fixed now.

**Comment by p1r473** [comment]
HI, looks like its back again @gyli 
I recommend adding a whitelist and then scripting the removal of the whitelist from your blocklist.
![image](https://user-images.githubusercontent.com/9235633/82756982-8edc6b80-9dab-11ea-8204-f6869009cd20.png)
